package com.model;
// Generated Dec 6, 2017 2:03:14 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Asignatura generated by hbm2java
 */
public class Asignatura  implements java.io.Serializable {


     private int id;
     private Usuarios usuarios;
     private String nombre;
     private String cod;
     private Integer userId;
     private Set<AsigEst> asigEsts = new HashSet<AsigEst>(0);

    public Asignatura() {
    }

	
    public Asignatura(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public Asignatura(Usuarios usuarios, String nombre, String cod, Integer userId, Set<AsigEst> asigEsts) {
       this.usuarios = usuarios;
       this.nombre = nombre;
       this.cod = cod;
       this.userId = userId;
       this.asigEsts = asigEsts;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getCod() {
        return this.cod;
    }
    
    public void setCod(String cod) {
        this.cod = cod;
    }
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    public Set<AsigEst> getAsigEsts() {
        return this.asigEsts;
    }
    
    public void setAsigEsts(Set<AsigEst> asigEsts) {
        this.asigEsts = asigEsts;
    }




}


