package com.model;
// Generated Dec 8, 2017 4:51:21 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Asignatura generated by hbm2java
 */
public class Asignatura  implements java.io.Serializable {


     private Integer id;
     private Usuarios usuarios;
     private String nombre;
     private String cod;
     private Set<AsigEst> asigEsts = new HashSet<AsigEst>(0);
     private Set<Seguimiento> seguimientos = new HashSet<Seguimiento>(0);

    public Asignatura() {
    }

    public Asignatura(Usuarios usuarios, String nombre, String cod, Set<AsigEst> asigEsts, Set<Seguimiento> seguimientos) {
       this.usuarios = usuarios;
       this.nombre = nombre;
       this.cod = cod;
       this.asigEsts = asigEsts;
       this.seguimientos = seguimientos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getCod() {
        return this.cod;
    }
    
    public void setCod(String cod) {
        this.cod = cod;
    }
    public Set<AsigEst> getAsigEsts() {
        return this.asigEsts;
    }
    
    public void setAsigEsts(Set<AsigEst> asigEsts) {
        this.asigEsts = asigEsts;
    }
    public Set<Seguimiento> getSeguimientos() {
        return this.seguimientos;
    }
    
    public void setSeguimientos(Set<Seguimiento> seguimientos) {
        this.seguimientos = seguimientos;
    }




}


