package com.model;
// Generated Dec 8, 2017 4:51:21 PM by Hibernate Tools 4.3.1



/**
 * Seguimiento generated by hbm2java
 */
public class Seguimiento  implements java.io.Serializable {


     private Integer id;
     private Asignatura asignatura;
     private Usuarios usuarios;
     private Integer porcentaje;
     private float nota;

    public Seguimiento() {
    }

    public Seguimiento(Asignatura asignatura, Usuarios usuarios, Integer porcentaje, Integer nota) {
       this.asignatura = asignatura;
       this.usuarios = usuarios;
       this.porcentaje = porcentaje;
       this.nota = nota;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Asignatura getAsignatura() {
        return this.asignatura;
    }
    
    public void setAsignatura(Asignatura asignatura) {
        this.asignatura = asignatura;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public Integer getPorcentaje() {
        return this.porcentaje;
    }
    
    public void setPorcentaje(Integer porcentaje) {
        this.porcentaje = porcentaje;
    }
    public float getNota() {
        return this.nota;
    }
    
    public void setNota(float nota) {
        this.nota = nota;
    }




}


